# 학습목표
* 배열과 리스트의 차이점
* 배열 생성 다루는 기법
* 기술 통계
* 결과에 대한 분석방법

* 넘파이의 배열은 모소 원소가 같은 자료형이어야 한다.
* resizing 이 안됨

* Vector(1차원 배열) - Pandas(Series)
* Matrix(2차원 행렬) - Pandas(DataFrame)

* 선형대수(행렬을 이용한 연산 가능)


In [8]:
import numpy as np

* 배열의 차원과 크기, 타입
* ndim , shape , dtype

In [10]:
def aryinfo(ary):
    print('type : {}'.format(type(ary)))
    print('shape : {}'.format(ary.shape))
    print('dimension : {}'.format(ary.ndim))
    print('dtype : {}'.format(ary.dtype))
    print('array data : \n', ary)

# 1차원 배열 생성
* array()

In [11]:
oneAry = np.array([0,1,2,3,4,5,6,7,8,9])
aryinfo(oneAry)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
array data : 
 [0 1 2 3 4 5 6 7 8 9]


* List vs Array 차이점(Vector operation)

In [12]:
data = [0,1,2,3,4,5,6,7,8,9]
data *2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
result = []
for d in data :
    result.append(d*2)
result

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
result2 = [d * 2 for d in data]
result2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
result3 = oneAry *2
result3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

* 벡터 연산은 비교, 산술, 논리 연산을 포함하는 모든 수학연산에 적용됨

In [16]:
xAry = np.array([1,2,3])
yAry = np.array([10,20,30])

In [18]:
2 * xAry + yAry

array([12, 24, 36])

In [19]:
xAry == 2

array([False,  True, False])

In [20]:
yAry > 20

array([False, False,  True])

In [21]:
(xAry == 2) & (yAry > 20)

array([False, False, False])

# 2차원 배열 생성

* ndarray(N-dimensional Array)
* 2차원, 3차원(다차원 배열 자료구조)
* 2차원 배열은 행렬(Matrix)
* list of list
* list of list of list

In [31]:
# 2개의 행과 3개의 열을 가지는 배열 만든다면
twoAry = np.array([[1,2,3],[4,5,6]],dtype = np.float64)
aryinfo(twoAry)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : float64
array data : 
 [[1. 2. 3.]
 [4. 5. 6.]]


In [170]:
# 행의 개수, 열의 개수
print(len(twoAry))
print(len(twoAry[0]))

2
3


# 3차원 배열 생성

In [43]:
# 2개의 3행 4열
threeAry = np.array([
                      [[1,2,3,4], 
                      [5,6,7,8], 
                      [9,10,11,12]],
                      [[13,14,15,16],
                       [17,18,19,20],
                       [21,22,23,24]                        
                      ]
                    ])
aryinfo(threeAry)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : int32
array data : 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [44]:
print('dept', len(threeAry))
print('row', len(threeAry[0]))
print('row', len(threeAry[1]))
print('row[0] col', len(threeAry[0][0]))

dept 2
row 3
row 3
row[0] col 4


* 요소의 타입을 변경할 때는 astype()

In [47]:
typeChange = threeAry.astype(np.float64)
aryinfo(typeChange)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : float64
array data : 
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]


In [49]:
indexAry = np.array([1,2,3,4,5,6,7])
aryinfo(indexAry)

type : <class 'numpy.ndarray'>
shape : (7,)
dimension : 1
dtype : int32
array data : 
 [1 2 3 4 5 6 7]


In [54]:
print(indexAry[0])
print(indexAry[-1])

1
7


In [57]:
# twoAry indexing

# 첫번째 행의 첫번째 열
print(twoAry[0,0])
# 첫번째 행의 두번째 열
print(twoAry[0,1])
# 마지막 행의 마지막 열
print(twoAry[-1,-1])

1.0
2.0
6.0


In [59]:
slicingAry = np.array([ [1,2,3,4], [5,6,7,8]  ])

# 첫번째 행의 전체
print(slicingAry[0,:])
# 두번째 열의 전체
print(slicingAry[:,1])
# 두번째 행의 두번째 열부터 끝까지
print(slicingAry[1,1:])

[1 2 3 4]
[2 6]
[6 7 8]


In [69]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
aryinfo(m)

# 이 행렬에서 값 7을 인덱싱한다
print(m[1,2])
# 이 행렬에서 값 14를 인덱싱한다
print(m[-1,-1])
# 이 행렬에서 배열 [6,7]을 슬라이싱한다
print(m[1,1:3])
# 이 행렬에서 배열 [7,12]을 슬라이싱한다
print(m[1:3,2])
# 이 행렬에서 배열 [[3,4], [8,9]]을 슬라이싱한다
print(m[0:2,3:5])

type : <class 'numpy.ndarray'>
shape : (3, 5)
dimension : 2
dtype : int32
array data : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


* fancy indexing
* boolean indexing

In [73]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
aryinfo(arr)
idx = np.array([True, False, True, False, True, False, True, False, True, False])
print(arr[idx])

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
array data : 
 [0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [76]:
arr % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [79]:
arr[arr % 2 == 0]  #불리언 인덱싱

array([0, 2, 4, 6, 8])

In [85]:
cntIdx = np.array([0,2,4,6,8])
print(arr[cntIdx])

[0 2 4 6 8]


In [86]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
aryinfo(x)
# 이 배열에서 3의 배수를 찾아라
print(x[x % 3 == 0])

# 이 배열에서 4로 나누면 1이 남는 수를 찾아라
print(x[x % 4 == 1])

# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라
print(x[(x % 3 ==0) & (x % 4 ==  1)])

type : <class 'numpy.ndarray'>
shape : (20,)
dimension : 1
dtype : int32
array data : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


In [90]:
# 배열에 index 배열을 전달하여 배열 요소를 참조해 보자
fancyAry = np.arange(0, 12, 1).reshape(3,4)
aryinfo(fancyAry)

type : <class 'numpy.ndarray'>
shape : (3, 4)
dimension : 2
dtype : int32
array data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [95]:
# 10값을 가져온다면?
fancyAry[2,2]

10

In [97]:
# 6값을 가져온다면?
fancyAry[1:2,2]

array([6])

In [107]:
aryinfo(fancyAry[1:2, 1:2])

type : <class 'numpy.ndarray'>
shape : (1, 1)
dimension : 2
dtype : int32
array data : 
 [[5]]


In [105]:
# 2와 10을 가져온다면?
aryinfo(fancyAry[[0,2],2])

type : <class 'numpy.ndarray'>
shape : (2,)
dimension : 1
dtype : int32
array data : 
 [ 2 10]


In [108]:
aryinfo(fancyAry[ [0,2], 2:3 ])

type : <class 'numpy.ndarray'>
shape : (2, 1)
dimension : 2
dtype : int32
array data : 
 [[ 2]
 [10]]


In [172]:
fancyAry[ [0,2],[0,2] ] # 0,2,8,10 나오게 추출해야하는데 이 방식으로는 안됨

array([ 0, 10])

In [113]:
rowIdx = np.array([0,2])
colIdx = np.array([0,2])
print(fancyAry[rowIdx][:,colIdx] )  # fancyAry[][] 형태이용

[[ 0  2]
 [ 8 10]]


# 배열 변형(타입, 형태)

In [116]:
x = np.array([1,2,3,] , dtype = 'U')
aryinfo(x)

type : <class 'numpy.ndarray'>
shape : (3,)
dimension : 1
dtype : <U1
array data : 
 ['1' '2' '3']


In [117]:
x[0] + x[1]

'12'

* inf vs NaN

In [121]:
np.array([0,1,-1,0] / np.array([1,0,0,0]) )

C:\Users\i\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\i\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

* zeros , ones
* zeros_like , ones_like
* empty
* arange
* linspace, logspace

* zeros : 크기가 정해져 있고 모든 값이 0인 배열을 생성하려면

In [129]:
z = np.zeros(5, dtype = 'U')
aryinfo(z)

type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
dtype : <U1
array data : 
 ['' '' '' '' '']


In [128]:
z = np.zeros((2,3), dtype = 'i')
aryinfo(z)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : int32
array data : 
 [[0 0 0]
 [0 0 0]]


In [132]:
o = np.ones((2,3,4), dtype = 'i8')
aryinfo(o)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : int64
array data : 
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [133]:
o_like = np.ones_like(o, dtype = 'f') #카피
aryinfo(o_like)

type : <class 'numpy.ndarray'>
shape : (2, 3, 4)
dimension : 3
dtype : float32
array data : 
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [134]:
z_like = np.zeros_like(z)
aryinfo(z_like)

type : <class 'numpy.ndarray'>
shape : (5,)
dimension : 1
dtype : <U1
array data : 
 ['' '' '' '' '']


In [137]:
e = np.empty((4,3))  #경로값 출력
aryinfo(e)

type : <class 'numpy.ndarray'>
shape : (4, 3)
dimension : 2
dtype : float64
array data : 
 [[0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]
 [0.0078125 0.0078125 0.0078125]]


In [138]:
a = np.arange(10)
aryinfo(a)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
array data : 
 [0 1 2 3 4 5 6 7 8 9]


In [139]:
a = np.arange(3,21,2)
aryinfo(a)

type : <class 'numpy.ndarray'>
shape : (9,)
dimension : 1
dtype : int32
array data : 
 [ 3  5  7  9 11 13 15 17 19]


* 전치행렬 : 행렬의 행은 열로, 열은 행으로 바꾼 행렬
* 속성 T 
* transpose opetion

In [141]:
arr = np.array([ [1,2,3,],[4,5,6] ])
aryinfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : int32
array data : 
 [[1 2 3]
 [4 5 6]]


In [142]:
arr_transpose = arr.T
aryinfo(arr_transpose)

type : <class 'numpy.ndarray'>
shape : (3, 2)
dimension : 2
dtype : int32
array data : 
 [[1 4]
 [2 5]
 [3 6]]


In [143]:
# Vector에 transpose 가능할까?
vec = np.arange(10)
aryinfo(vec)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
array data : 
 [0 1 2 3 4 5 6 7 8 9]


In [144]:
vec_transpose = vec.T  # 가능하지만 의미가 없음 
aryinfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (10,)
dimension : 1
dtype : int32
array data : 
 [0 1 2 3 4 5 6 7 8 9]


In [146]:
vec_transpose = vec.reshape(1,10).T
aryinfo(vec_transpose)

type : <class 'numpy.ndarray'>
shape : (10, 1)
dimension : 2
dtype : int32
array data : 
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


* 배열의 원소를 순차적으로 access 하고자 한다면?
* for (Vector , Matrix)
* iterator(internext(), finished 속성을 이용해서 ndarray 모든 요소를 순차적으로 접근할 수 있다)

In [148]:
arr = np.array([1,2,3,4,5])

In [151]:
for tmp in arr :
    print(tmp, end=" ")

1 2 3 4 5 

In [152]:
for idx in range(len(arr)):
    print(arr[idx], end=" ")

1 2 3 4 5 

In [156]:
# ite = np.nditer(arr, flags=['c_index'])
# while not ite.finished :
#     print(arr[ite.index], end=" ")
#     ite.iternext()

1 2 3 4 5 

In [158]:
arr = np.array([ [1,2,3],[4,5,6] ])
aryinfo(arr)

type : <class 'numpy.ndarray'>
shape : (2, 3)
dimension : 2
dtype : int32
array data : 
 [[1 2 3]
 [4 5 6]]


In [166]:
# 2차원 배열에 대한 순차적 접근 코드 작성
# print(arr.shape[0]) : row
# print(arr.shape[1]) : col

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]) :
        print(arr[i][j] , end = '\n')
    print('\n')

1
2
3


4
5
6




In [167]:
ite = np.nditer(arr, flags=['multi_index'])
while not ite.finished :
    print(arr[ite.multi_index], end= " ")
    ite.iternext()

1 2 3 4 5 6 